accepted = [
    "Apache-2.0",
    "MIT",
    "AGPL-3.0-only",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "BSL-1.0",
    "MPL-2.0",
    "CC0-1.0",
    "NCSA",
    "ISC",
    "0BSD",
    "Unicode-3.0",
]

#threshold = 1.0
#[licenses]
#self_cell = "Apache-2.0 OR GPL-2.0-only"
#name = "self_cell"
#expression = "Apache-2.0"
