[package]
name = "positive_toolbox"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = [
    "x11",
    "thread-pool",
    "wgpu",
    "linux-theme-detection",
] }
