name: commit-build

on:
  push:
    paths-ignore: 
      - 'README.md'
      - 'READMEs/**'
      - '.vscode/**'
      - 'TODO.md'

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # - name: Install Rust Toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true

      - name: install rustup (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://win.rustup.rs" -OutFile "rustup-init.exe"
          ls
          .\rustup-init.exe -y --profile minimal

      - name: install rustup (Linux)
        if: runner.os == 'Linux'
        run: |
          curl https://sh.rustup.rs -o rust-init.sh
          sh rust-init.sh -y

      - name: check rust Install
        run: |
          rustc --version
          cargo --version

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: check uv install
        run: |
          uv self version

      - name: debug build
        run: cargo build

      - name: release build
        run: cargo build --release

      - name: zip files (Linux)
        id: zip_files_linux
        run: |
          file=$(uv run ci/zip_files.py)
          echo "zip_path=$file" >> $GITHUB_OUTPUT

      - name: zip files (Windows)
        id: zip_files_windows
        run: |
          $file = (uv run ci/zip_files.py)
          echo "zip_path=$file" >> $env:GITHUB_OUTPUT

      - name: Upload exe artifact (Linux)
        uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          path: ${{ steps.zip_files_linux.outputs.zip_path }}

      - name: Upload exe artifact (Windows)
        uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          path: ${{ steps.zip_files_windows.outputs.zip_path }}
